### ISSUE TITLE
OR 2023 Joint Child Care 20K+10K

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#132]
OR 2023 Joint Child Care 20K+10K

I have used a 4 year old child in this example.

http://taxsim.nber.org/out2psl/or4

Emulator shows siitax of 559 while TaxAct shows refund of 724. I think my attempts to diagnose the emulator are probably a distraction from anything helpful, so I won't speculate as to the cause.

**Comment by noman404** [comment]
```
- name: 31-OR.yaml
  absolute_error_margin: 2
  period: 2023
  input:
    people:
      person1:
        age: 23
        employment_income: 20000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person2:
        age: 23
        employment_income: 10000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 4
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 41
  output:
    income_tax: -5294.58
    or_income_tax: -721.39
    employee_social_security_tax: 2295
    employee_medicare_tax: 435
    additional_medicare_tax: 435
    taxsim_tfica: 2295
    adjusted_gross_income: 30000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27700
    exemptions: 0
    taxable_income_deductions_if_itemizing: 1655.22
    taxable_income: 2300
    income_tax_main_rates: 230
    ctc: 2000
    refundable_ctc: 1600
    cdcc: 540
    eitc: 3694.58
    amt_income: 30000
    alternative_minimum_tax: 0
    capital_gains_tax: 230
    household_net_income: 37722.8
    or_agi: 30000
    or_standard_deduction: 5210
    or_itemized_deductions: 0
    or_taxable_income: 24790
    or_property_tax_credit: 0
    or_cdcc: 0
    or_eitc: 332.51
    state_non_refundable_credits: 2320.51
    state_refundable_credits: 2320.51
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
