### ISSUE TITLE
GA 2023 Joint 20K 10K 2K child care

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#148]
GA 2023 Joint 20K 10K 2K child care

http://taxsim.nber.org/out2psl/ga

Emulator shows tax of 484, TaxAct shows 415.

**Comment by noman404** [comment]
```
- name: 29-GA.yaml
  absolute_error_margin: 2
  period: 2023
  input:
    people:
      person1:
        age: 23
        employment_income: 20000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person2:
        age: 23
        employment_income: 10000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 4
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 13
  output:
    income_tax: -5294.58
    ga_income_tax: 321.75
    employee_social_security_tax: 2295
    employee_medicare_tax: 435
    additional_medicare_tax: 435
    taxsim_tfica: 2295
    adjusted_gross_income: 30000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27700
    exemptions: 0
    taxable_income_deductions_if_itemizing: 783.5
    taxable_income: 2300
    income_tax_main_rates: 230
    ctc: 2000
    refundable_ctc: 1600
    cdcc: 540
    eitc: 3694.58
    amt_income: 30000
    alternative_minimum_tax: 0
    capital_gains_tax: 230
    household_net_income: 35595.4
    ga_agi: 30000
    ga_standard_deduction: 7100
    n/a: 0
    ga_taxable_income: 12500
    ga_property_tax_credit: 0
    ga_cdcc: 162
    ga_eitc: 0
    state_non_refundable_credits: 162
    state_refundable_credits: 162
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
