### ISSUE TITLE
OK 20K 10K 2K child care

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#151]
OK 20K 10K 2K child care

http://taxsim.nber.org/out2psl/ok

Note unusual EIC provision: https://www.freetaxusa.com/answers?faq=10660 Oklahoma does not use 2023 EIC formula.

Emulator shows  refund of 80, TaxAct shows 16.

**Comment by noman404** [comment]
@feenberg is this link has valid input, cause in there i do not see 20k 10k 2k values 

```
year,state,age1,depx,pwages,mstat,mortgage,taxsimid,idtl
2023,37,0,0,1000000,1,0,21,2
```

**Comment by feenberg** [comment]
URL should have been:

 http://taxsim.nber.org/out2psl/ok2

Sorry.

**Comment by noman404** [comment]
```
- name: 1-OK.yaml
  absolute_error_margin: 2
  period: 2023
  input:
    people:
      person1:
        age: 23
        employment_income: 20000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person2:
        age: 23
        employment_income: 10000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 4
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 40
  output:
    income_tax: -5294.58
    ok_income_tax: -88.48
    employee_social_security_tax: 2295
    employee_medicare_tax: 435
    additional_medicare_tax: 435
    taxsim_tfica: 2295
    adjusted_gross_income: 30000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27700
    exemptions: 0
    taxable_income_deductions_if_itemizing: 493.75
    taxable_income: 2300
    income_tax_main_rates: 230
    ctc: 2000
    refundable_ctc: 1600
    cdcc: 540
    eitc: 3694.58
    amt_income: 30000
    alternative_minimum_tax: 0
    capital_gains_tax: 230
    household_net_income: 37089.8
    ok_agi: 30000
    ok_standard_deduction: 12700
    ok_itemized_deductions: 0
    ok_taxable_income: 14300
    ok_property_tax_credit: 0
    ok_cdcc: 0
    ok_eitc: 184.73
    state_non_refundable_credits: 0
    state_refundable_credits: 0
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
