### ISSUE TITLE
CT 2022 Joint 3 deps

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#168]
CT 2022 Joint 3 deps

http://taxsim.nber.org/out2psl/ct

Emulator shows 4709 siitax but TaxAct shows 5459 for taxpayer with 3 dependents and 113430 wages.

**Comment by noman404** [comment]
```
- name: 0-CT.yaml
  absolute_error_margin: 2
  period: 2022
  input:
    people:
      person1:
        age: 40
        employment_income: 113430
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person2:
        age: 40
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 9
  output:
    income_tax: 4490.6
    ct_income_tax: 4708.65
    employee_social_security_tax: 8677.39
    employee_medicare_tax: 1644.73
    additional_medicare_tax: 1644.73
    taxsim_tfica: 8677.39
    adjusted_gross_income: 113430
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 25900
    exemptions: 0
    taxable_income_deductions_if_itemizing: 4963.65
    taxable_income: 87530
    income_tax_main_rates: 10490.6
    ctc: 6000
    refundable_ctc: 0
    cdcc: 0
    eitc: 0
    amt_income: 113430
    alternative_minimum_tax: 0
    capital_gains_tax: 10490.6
    household_net_income: 95553.4
    ct_agi: 113430
    ct_standard_deduction: 0
    ct_itemized_deductions: 0
    ct_taxable_income: 113430
    ct_property_tax_credit: 0
    ct_cdcc: 0
    ct_eitc: 0
    state_non_refundable_credits: 750
    state_refundable_credits: 750
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
