### ISSUE TITLE
DE 2022 Joint 3deps 142000wages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#169]
DE 2022 Joint 3deps 142000wages

  http://taxsim.nber.org/out2psl/de

Emulator shows 6776 while TaxAct shows 7377.

**Comment by noman404** [comment]
```
- name: 10-DE.yaml
  absolute_error_margin: 2
  period: 2022
  input:
    people:
      person1:
        age: 40
        employment_income: 142000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person2:
        age: 40
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 10
  output:
    income_tax: 10776
    de_income_tax: 6776.5
    employee_social_security_tax: 10863
    employee_medicare_tax: 2059
    additional_medicare_tax: 2059
    taxsim_tfica: 10863
    adjusted_gross_income: 142000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 25900
    exemptions: 0
    taxable_income_deductions_if_itemizing: 8141
    taxable_income: 116100
    income_tax_main_rates: 16776
    ctc: 6000
    refundable_ctc: 0
    cdcc: 0
    eitc: 0
    amt_income: 142000
    alternative_minimum_tax: 0
    capital_gains_tax: 16776
    household_net_income: 113584
    de_agi: 0
    de_standard_deduction_joint: 6500
    de_itemized_deductions_joint: 0
    de_taxable_income_joint: 135500
    de_property_tax_credit: 0
    de_cdcc: 0
    de_eitc: 0
    state_non_refundable_credits: 1150
    state_refundable_credits: 1150
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
