### ISSUE TITLE
GA Joint 2022 200K wage 3 deps 40K mortgage 1 70yo

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#175]
GA Joint 2022 200K wage 3 deps 40K mortgage 1 70yo

See

http://taxsim.nber.org/out2psl/ga2

Emulator shows GA Taxable Income of $129,000 while TaxAct shows $139,000.  siitax is off by about $500, which is explained by the Taxable Income difference.

**Comment by noman404** [comment]
```
- name: 194-GA.yaml
  absolute_error_margin: 2
  period: 2022
  input:
    people:
      person1:
        age: 70
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 40000
      person2:
        age: 40
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 13
  output:
    income_tax: 18234
    ga_income_tax: 7217
    employee_social_security_tax: 12014
    employee_medicare_tax: 2900
    additional_medicare_tax: 2900
    taxsim_tfica: 12014
    adjusted_gross_income: 200000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27300
    exemptions: 0
    taxable_income_deductions_if_itemizing: 50000
    taxable_income: 150000
    income_tax_main_rates: 24234
    ctc: 6000
    refundable_ctc: 0
    cdcc: 0
    eitc: 0
    amt_income: 160000
    alternative_minimum_tax: 0
    capital_gains_tax: 24234
    household_net_income: 162535
    ga_agi: 196000
    ga_standard_deduction: 8400
    ga_itemized_deductions: 0
    ga_taxable_income: 129600
    ga_property_tax_credit: 0
    ga_cdcc: 0
    ga_eitc: 0
    state_non_refundable_credits: 0
    state_refundable_credits: 0
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
