### ISSUE TITLE
AZ 2022 Joint 200K wage 40K mortgage 3 deps

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#176]
AZ 2022 Joint 200K wage 40K mortgage 3 deps

See 

http://taxsim.nber.org/out2psl/az

Emulator shows State Taxable Income of $152,449 while TaxAct reports $157,900.

**Comment by noman404** [comment]
```
- name: 194-AZ.yaml
  absolute_error_margin: 2
  period: 2022
  input:
    people:
      person1:
        age: 70
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 40000
      person2:
        age: 40
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 4
  output:
    income_tax: 19234.8
    az_income_tax: 3996.57
    employee_social_security_tax: 12014
    employee_medicare_tax: 2900
    additional_medicare_tax: 2900
    taxsim_tfica: 12014
    adjusted_gross_income: 200000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27300
    exemptions: 0
    taxable_income_deductions_if_itemizing: 45450.9
    taxable_income: 154549
    income_tax_main_rates: 25234.8
    ctc: 6000
    refundable_ctc: 0
    cdcc: 0
    eitc: 0
    amt_income: 160000
    alternative_minimum_tax: 0
    capital_gains_tax: 25234.8
    household_net_income: 164755
    az_agi: 197900
    az_standard_deduction: 25900
    az_itemized_deductions: 45450.9
    az_taxable_income: 152449
    az_property_tax_credit: 0
    az_cdcc: 0
    az_eitc: 0
    state_non_refundable_credits: 300
    state_refundable_credits: 300
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
