### ISSUE TITLE
MO 2022 Joint 2X200K wage 3Xdep 40K mortgage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#177]
MO 2022 Joint 2X200K wage 3Xdep 40K mortgage

See

http://taxsim.nber.org/out2psl/mo

Emulator shows Taxable income of $167,311 while TaxAct shows that amount for each partner. I think v36 should be the sum ( $344,622). For example, siitax shows the sum of taxpayer and spouse.

**Comment by noman404** [comment]
```
- name: 194-MO.yaml
  absolute_error_margin: 0.01
  period: 2022
  input:
    people:
      person1:
        age: 70
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        age: 40
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 29
  output:
    income_tax: 66463
    mo_income_tax: 17367.3
    employee_social_security_tax: 25378
    employee_medicare_tax: 7150
    additional_medicare_tax: 7150
    taxsim_tfica: 25378
    adjusted_gross_income: 400000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27300
    exemptions: 0
    taxable_income_deductions_if_itemizing: 50000
    taxable_income: 350000
    income_tax_main_rates: 72463
    ctc: 6000
    refundable_ctc: 0
    cdcc: 0
    eitc: 0
    amt_income: 360000
    alternative_minimum_tax: 0
    capital_gains_tax: 72463
    household_net_income: 290792
    mo_agi: 0
    mo_standard_deduction: 0
    mo_itemized_deductions: 65378
    mo_taxable_income: 334622
    mo_property_tax_credit: 0
    mo_cdcc: 0
    mo_eitc: 0
    state_non_refundable_credits: 0
    state_refundable_credits: 0
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
