### ISSUE TITLE
HI 2022 Joint 2x200K wage 3xdepx 40K mortgage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#179]
HI 2022 Joint 2x200K wage 3xdepx 40K mortgage

See 

http://taxsim.nber.org/out2psl/hi3

Emulator shows state Taxable Income of $351866 while TaxAct shows $360,132.

**Comment by noman404** [comment]
```
- name: 194-HI.yaml
  absolute_error_margin: 0.01
  period: 2022
  input:
    people:
      person1:
        age: 70
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        age: 40
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 15
  output:
    income_tax: 66463
    hi_income_tax: 27943.9
    employee_social_security_tax: 25378
    employee_medicare_tax: 7150
    additional_medicare_tax: 7150
    taxsim_tfica: 25378
    adjusted_gross_income: 400000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27300
    exemptions: 0
    taxable_income_deductions_if_itemizing: 50000
    taxable_income: 350000
    income_tax_main_rates: 72463
    ctc: 6000
    refundable_ctc: 0
    cdcc: 0
    eitc: 0
    amt_income: 360000
    alternative_minimum_tax: 0
    capital_gains_tax: 72463
    household_net_income: 280215
    hi_agi: 400000
    hi_standard_deduction: 4400
    hi_itemized_deductions: 41269.2
    hi_taxable_income: 351867
    hi_property_tax_credit: 0
    hi_cdcc: 0
    hi_eitc: 0
    state_non_refundable_credits: 0
    state_refundable_credits: 0
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
