### ISSUE TITLE
DC Joint 2022 2x200K wage 3x depx 40K mortgage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#180]
DC Joint 2022 2x200K wage 3x depx 40K mortgage

See

http://taxsim.nber.org/out2psl/dc2

Emulator shows Taxable Income of zero, should be $360,000.

**Comment by noman404** [comment]
Variable `dc_taxable_income `does not exist thus it shows 0.0

@PavelMakarchuk here's the yaml log

```
- name: 194-DC.yaml
  absolute_error_margin: 0.01
  period: 2022
  input:
    people:
      person1:
        age: 70
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        age: 40
        employment_income: 200000
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 11
  output:
    income_tax: 66463
    dc_income_tax: 28250
    employee_social_security_tax: 25378
    employee_medicare_tax: 7150
    additional_medicare_tax: 7150
    taxsim_tfica: 25378
    adjusted_gross_income: 400000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27300
    exemptions: 0
    taxable_income_deductions_if_itemizing: 50000
    taxable_income: 350000
    income_tax_main_rates: 72463
    ctc: 6000
    refundable_ctc: 0
    cdcc: 0
    amt_income: 360000
    alternative_minimum_tax: 0
    capital_gains_tax: 72463
    household_net_income: 279909
    state_non_refundable_credits: 0
    state_refundable_credits: 0
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
