### ISSUE TITLE
CT 2022 Joint 1x71K wage 3xdepx 30K mortgage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#193]
CT 2022 Joint 1x71K wage 3xdepx 30K mortgage

Emulator shows siitax of 2040 while TaxAct shows 2789

[a and b a 2022 Connecticut Form CT-1040.pdf](https://github.com/user-attachments/files/18307487/a.and.b.a.2022.Connecticut.Form.CT-1040.pdf)

[a and b a 2022 Connecticut Form CT-1040TCS.pdf](https://github.com/user-attachments/files/18307488/a.and.b.a.2022.Connecticut.Form.CT-1040TCS.pdf)

Our server is down, so I don't have a way to upload the Emulator output, but the input is

depx,mortgage,mstat,pwages,state,swages,year
3,30000,2,71000,7,0,2022

**Comment by noman404** [comment]
```
- name: 0-CT.yaml
  absolute_error_margin: 0.01
  period: 2022
  input:
    people:
      person1:
        age: 40
        employment_income: 71000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        age: 40
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        age: 10
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 9
  output:
    income_tax: -1806.6
    ct_income_tax: 2040
    employee_social_security_tax: 5431.5
    employee_medicare_tax: 1029.5
    additional_medicare_tax: 1029.5
    taxsim_tfica: 5431.5
    income_tax_main_rates: 4193.4
    capital_gains_tax: 4193.4
    state_non_refundable_credits: 750
    state_refundable_credits: 750
```
