### ISSUE TITLE
NJ Joint 2021 100Kwage 30Kmortgage 10Kproptax 3depx

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#208]
NJ Joint 2021 100Kwage 30Kmortgage 10Kproptax 3depx

See

http://taxsim.nber.org/out2psl/nj4

Emulator shows Taxable Income (v36) of 93,500 while TaxAct shows $83,500. Difference is proptax.

**Comment by feenberg** [comment]
Nice log output. I will include this in my issue reports.

Actually, when I was suggesting not imitating the Taxsim version of 
idtl=5, but using something you already had, it was something like this I 
was thinking of. I don't know why you didn't offer it.

Daniel Feenberg

**Comment by noman404** [comment]
@feenberg the `yaml ` test files content should look like below, but somehow yours has the last part only, can you check is there any content missing when uploading?  Also the states code is `26=MO` input file shared 

```
- name: 20-NJ.yaml
  absolute_error_margin: 2
  period: 2023
  input:
    people:
      person1:
        age: 23
        employment_income: 20000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person2:
        age: 23
        employment_income: 10000
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
      person3:
        age: 4
        employment_income: 0
        ssi: 0
        state_supplement: 0
        wic: 0
        deductible_mortgage_interest: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        tax_unit_childcare_expenses: 0
        premium_tax_credit: 0
        local_income_tax: 0
        state_sales_tax: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 34
  output:
    income_tax: -5294.58
    nj_income_tax: -2354.08
    employee_social_security_tax: 2295
    employee_medicare_tax: 435
    additional_medicare_tax: 435
    taxsim_tfica: 2295
    adjusted_gross_income: 30000
    tax_unit_taxable_unemployment_compensation: 0
    tax_unit_taxable_social_security: 0
    standard_deduction: 27700
    exemptions: 0
    taxable_income_deductions_if_itemizing: 392
    taxable_income: 2300
    income_tax_main_rates: 230
    ctc: 2000
    refundable_ctc: 1600
    cdcc: 540
    eitc: 3694.58
    amt_income: 30000
    alternative_minimum_tax: 0
    capital_gains_tax: 230
    household_net_income: 39355.4
    nj_agi: 30000
    n/a: 0
    nj_taxable_income: 26500
    nj_property_tax_credit: 0
    nj_cdcc: 270
    nj_eitc: 1477.83
    state_non_refundable_credits: 2747.83
    state_refundable_credits: 2747.83
    qualified_business_income_deduction: 0
    net_investment_income_tax: 0
    recovery_rebate_credit: 0
```
